name: Q4
on: [push]
permissions:
  contents: write
jobs:
  archive-q4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create archive file
        run: |
          DATE=$(date +'%d-%m-%Y')
          echo "Nom : Félix le gars" > Q4_archive_${DATE}.txt
          cat Q4.java >> Q4_archive_${DATE}.txt
      - name: Commit and push
        run: |
          git config --global user.name "Vocif3r"
          git config --global user.email "felixlgrs.dev@gmail.com"
          git add Q4_archive_*.txt
          git commit -m "Ajout de Q4_archive_date"
          git push